version: '3'
services:
  tor:
    build: ./tor_docker
    restart: always
    depends_on:
      - web # tor requires the hostname of web
    volumes:
      - ./tor_docker/torrc:/etc/tor/torrc
    healthcheck:
      test: ['CMD-SHELL', "pidof tor"]
    networks:
      - external_network
      - internal_network
  
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    build: .
    image: ghcr.io/mastodon/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "sudo /bin/redsocks_prepare.sh; rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - db
      - redis
      # - es
    volumes:
      - ./public/system:/mastodon/public/system
      - ./redsocks.conf:/etc/redsocks.conf
      - ./redsocks_prepare_sync.sh:/bin/redsocks_prepare_sync.sh
    cap_add: ["NET_ADMIN"]

  streaming:
    build: .
    image: ghcr.io/mastodon/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "sudo /bin/redsocks_prepare.sh; node ./streaming"
    networks:
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    volumes:
      - ./redsocks.conf:/etc/redsocks.conf
      - ./redsocks_prepare_sync.sh:/bin/redsocks_prepare_sync.sh
    cap_add: ["NET_ADMIN"]
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: ghcr.io/mastodon/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "sudo /bin/redsocks_prepare.sh; bundle exec sidekiq"
    depends_on:
      - db
      - redis
    networks:
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
      - ./redsocks.conf:/etc/redsocks.conf
      - ./redsocks_prepare_sync.sh:/bin/redsocks_prepare_sync.sh
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    cap_add: ["NET_ADMIN"]
  
  postfix:
    build: ./postfix
    restart: always
    command: bash -c "sh /bin/redsocks_prepare_sync.sh; postfix start; sleep infinity"
    environment:
      - MAILSERVICE=yeah
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/aliases:/etc/aliases
      - ./redsocks.conf:/etc/redsocks.conf
      - ./redsocks_prepare_sync.sh:/bin/redsocks_prepare_sync.sh
    networks:
      - internal_network
    healthcheck:
      interval: 2m
      timeout: 2m
      test: ['CMD-SHELL', "bash -c \"sleep 60; echo QUIT\" | telnet localhost 25 | grep -i \"^220\""]
    cap_add: ["NET_ADMIN"]
  
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/onionginx.conf:/etc/nginx/conf.d/onionginx.conf
      - ./ssl_certificate:/etc/ssl_certificate
    networks:
      - internal_network
  
  dnsservice:
    restart: always
    tty: true
    build: ./dnsservice
    environment:
      - DNSSERVICE=yeah
    command: bash -c "LOCAL_ADDR=$$(head -n 1 /etc/resolv.conf | awk '{print $$2}'); TOR_ADDR=$(dig +short tor); sh /bin/redsocks_prepare_sync.sh; python3 proxy.py --upstream_local $$LOCAL_ADDR --upstream_tor $$TOR_ADDR --upstream_surface 127.0.0.1:5300 --timeout 120"
    volumes:
      - ./dnsservice/proxy.py:/proxy.py
      - ./redsocks.conf:/etc/redsocks.conf
      - ./redsocks_prepare_sync.sh:/bin/redsocks_prepare_sync.sh
    networks:
      - internal_network
    cap_add: ["NET_ADMIN"]

networks:
  external_network:
  internal_network:
    internal: true
